SRC		= 	./src/string/ft_strchr.c \
			./src/string/ft_split.c \
			./src/string/ft_strtrim.c \
			./src/string/ft_strnstr.c \
			./src/string/ft_strmapi.c \
			./src/string/ft_atol.c \
			./src/string/ft_strdup.c \
			./src/string/ft_substr.c \
			./src/string/ft_strlcpy.c \
			./src/string/ft_ltoa.c \
			./src/string/ft_strlen.c \
			./src/string/ft_strlcat.c \
			./src/string/ft_strrchr.c \
			./src/string/ft_strncmp.c \
			./src/string/ft_strjoin.c \
			./src/memory/ft_bzero.c \
			./src/memory/ft_memchr.c \
			./src/memory/ft_memset.c \
			./src/memory/ft_calloc.c \
			./src/memory/ft_memccpy.c \
			./src/memory/ft_memcmp.c \
			./src/memory/ft_memcpy.c \
			./src/memory/ft_memmove.c \
			./src/ctype/ft_tolower.c \
			./src/ctype/ft_toupper.c \
			./src/ctype/ft_isprint.c \
			./src/ctype/ft_isascii.c \
			./src/ctype/ft_isdigit.c \
			./src/ctype/ft_isalpha.c \
			./src/ctype/ft_isalnum.c \
			./src/stdio/ft_putnbr_fd.c \
			./src/stdio/ft_putchar_fd.c \
			./src/stdio/ft_putendl_fd.c \
			./src/stdio/ft_putstr_fd.c \
			./src/linked_list/ft_lstiter.c \
			./src/linked_list/ft_lstdelone.c \
			./src/linked_list/ft_lstlast.c \
			./src/linked_list/ft_lstsize.c \
			./src/linked_list/ft_lstmap.c \
			./src/linked_list/ft_lstnew.c \
			./src/linked_list/ft_lstadd_back.c \
			./src/linked_list/ft_lstclear.c \
			./src/linked_list/ft_lstadd_front.c
