version: "3.9"
services:
# === NGINX ===
  nginx:
    container_name: "nginx"
    hostname: "nginx"
    # env_file: DOES NGINX NEED IT ? SECURITY 
    #   - .env
    build:
      context:  "./nginx"
      dockerfile: Dockerfile
    ports:
      - "443:443"
    expose:
      - "9000"
    networks:
      - inception_net
    volume:
      - "wordpress_vol:/var/www/localhost:ro"
    restart: unless-stopped
# === WordPress ===
  wordpress:
    depends_on:
      - "mariadb"
    container_name: "wordpress"
    hostname: "wordpress"
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    build:
      context:  "./wordpress"
      dockerfile: Dockerfile
    expose:
      - "3306"
      - "9000"
    networks:
      - inception_net
    volume:
      - "wordpress_vol:/var/www/localhost"
      - "mariadb_vol:/var/lib/mysql"
    restart: unless-stopped
# === MariaDB ===
  mariadb:
    container_name: "mariadb"
    hostname: "mariadb"
    env_file:
      - .env
    build:
      context:  "./mariadb"
      dockerfile: Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: mysql_root_pass #TODO: use env
      MYSQL_DATABASE: db_name #TODO: use env
      MYSQL_USER: user_name #TODO: use env
      MYSQL_PASSWORD: user_pass #TODO: use env
    expose:
      - "3306"
    networks:
      - inception_net
    volume:
      - "mariadb_vol:/var/lib/mysql"
    restart: unless-stopped
# === Volumes ===
volumes:
  wordpress_vol:
    driver: "local"
    driver_opts:
        type: "bind"
        src: "/home/tderwedu/data/wordpress"
  mariadb_vol:
    driver: "local"
    driver_opts:
        type: "bind"
        src: "/home/tderwedu/data/mariadb"
# === Network ===
networks:
  inception_net:
    name: "inception_net"
    driver: bridge
