version: "3.8"
services:
# === NGINX ===
  nginx:
    container_name: "nginx"
    hostname: "nginx"
    build:
      context:  "./requirements/nginx"
      dockerfile: Dockerfile
    ports:
      - "443:443"
    expose:
      - "9000"
    networks:
      - inception_net
    volumes:
      - "wordpress_vol:/var/www/localhost"
    restart: unless-stopped
# === MariaDB ===
  mariadb:
    container_name: "mariadb"
    hostname: "mariadb"
    env_file: .env
    build:
      context:  "./requirements/mariadb"
      dockerfile: Dockerfile
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    networks:
      - inception_net
    volumes:
      - "mariadb_vol:/var/lib/mysql"
    restart: unless-stopped
# === WordPress ===
  wordpress:
    depends_on:
      - "mariadb"
    container_name: "wordpress"
    hostname: "wordpress"
    env_file: .env
    build:
      context:  "./requirements/wordpress"
      dockerfile: Dockerfile
    expose:
      - "3306"
      - "9000"
    networks:
       - inception_net
    volumes:
      - "wordpress_vol:/var/www/localhost"
    restart: unless-stopped
# === Volumes ===
volumes:
  wordpress_vol:
    driver: "local"
    driver_opts:
      type: 'none'
      o: "bind"
      device: "/home/tderwedu/data/wordpress_vol"
  mariadb_vol:
    driver: "local"
    driver_opts:
      type: 'none'
      o: "bind"
      device: "/home/tderwedu/data/mariadb_vol"
# === Network ===
networks:
  inception_net:
    name: "inception_net"
    driver: bridge
