version: "3.8"
services:

# === NGINX ===

  nginx:
    container_name: nginx
    hostname: nginx
    image: nginx
    depends_on:
      - wordpress
      - website
      - adminer
      - phpredisadmin
    build:
      context:  "./requirements/nginx"
    ports:
      - "443:443"
    expose:
      - "9000"
    networks:
      - inception_net
    volumes:
      - "wordpress_vol:/var/www/tderwedu.42.fr"
      - "adminer_vol:/var/www/adminer"
      - "website_vol:/var/www/website"
      - "phpredisadmin_vol:/var/www/phpredisadmin"
    restart: unless-stopped

# === MariaDB ===

  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb
    env_file: .env
    build:
      context:  "./requirements/mariadb"
      args:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    expose:
      - "3306"
    networks:
      - inception_net
    volumes:
      - "mariadb_vol:/var/lib/mysql"
    restart: unless-stopped

# === WordPress ===

  wordpress:
    container_name: wordpress
    hostname: wordpress
    image: wordpress
    depends_on:
      - mariadb
      - redis
    env_file: .env
    build:
      context:  "./requirements/wordpress"
    expose:
      - "3306"
      - "9000"
    networks:
       - inception_net
    volumes:
      - "wordpress_vol:/var/www/tderwedu.42.fr"
    restart: unless-stopped

# === Redis ===

  redis:
    container_name: redis
    hostname: redis
    image: redis
    build:
        context: ./requirements/bonus/redis
    depends_on:
        - mariadb
    expose:
        - "6379"
    networks:
        - inception_net
    restart: unless-stopped

# === FTP  ===

  ftp:
    container_name: ftp 
    hostname: ftp 
    image: ftp 
    depends_on:
      - wordpress
    build:
        context: ./requirements/bonus/ftp
    networks:
        - inception_net
    ports:
      - "20:20"
    volumes:
      - "wordpress_vol:/home/tderwedu/"
    restart: unless-stopped

# === Website ===

  website:
    container_name: website
    hostname: website
    image: website
    build:
      context: ./requirements/bonus/website
    expose:
      - "80"
    networks:
      - inception_net
    volumes:
      - "website_vol:/var/www/website"
    restart: unless-stopped

# === Adminer  ===

  adminer:
    container_name: adminer 
    hostname: adminer 
    image: adminer 
    depends_on:
      - mariadb
    build:
        context: ./requirements/bonus/adminer
    networks:
        - inception_net
    volumes:
     - "adminer_vol:/var/www/adminer"
    restart: unless-stopped

# === phpRedisAdmin  ===

  phpredisadmin:
    container_name: phpredisadmin 
    hostname: phpredisadmin 
    image: phpredisadmin 
    depends_on:
      - redis
    build:
        context: ./requirements/bonus/phpredisadmin
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    networks:
        - inception_net
    volumes:
     - "phpredisadmin_vol:/var/www/phpredisadmin"
    restart: unless-stopped

# === Volumes ===

volumes:
  wordpress_vol:
    driver: "local"
    driver_opts:
      type: 'none'
      o: "bind"
      device: "/home/tderwedu/data/wordpress_vol"
  mariadb_vol:
    driver: "local"
    driver_opts:
      type: 'none'
      o: "bind"
      device: "/home/tderwedu/data/mariadb_vol"
  adminer_vol:
    driver: "local"
    driver_opts:
      type: 'none'
      o: "bind"
      device: "/home/tderwedu/data/adminer_vol"
  website_vol:
    driver: "local"
    driver_opts:
      type: 'none'
      o: "bind"
      device: "/home/tderwedu/data/website_vol"
  phpredisadmin_vol:
    driver: "local"
    driver_opts:
      type: 'none'
      o: "bind"
      device: "/home/tderwedu/data/phpredisadmin_vol"

# === Network ===

networks:
  inception_net:
    name: ${NET_NAME}
    driver: bridge
