SRC		= 	./src/ctype/ft_isprint.c\
			./src/ctype/ft_tolower.c\
			./src/ctype/ft_toupper.c\
			./src/ctype/ft_isascii.c\
			./src/ctype/ft_isdigit.c\
			./src/ctype/ft_isalpha.c\
			./src/ctype/ft_isalnum.c\
			./src/grisu/ft_cachedpower.c\
			./src/grisu/ft_digit_gen_no_div.c\
			./src/grisu/ft_kcomp.c\
			./src/linked_list/ft_lstiter.c\
			./src/linked_list/ft_lstdelone.c\
			./src/linked_list/ft_lstlast.c\
			./src/linked_list/ft_lstsize.c\
			./src/linked_list/ft_lstmap.c\
			./src/linked_list/ft_lstnew.c\
			./src/linked_list/ft_lstadd_back.c\
			./src/linked_list/ft_lstclear.c\
			./src/linked_list/ft_lstadd_front.c\
			./src/math/ft_ceil.c\
			./src/math/ft_floor.c\
			./src/memory/ft_bzero.c\
			./src/memory/ft_memchr.c\
			./src/memory/ft_memset.c\
			./src/memory/ft_calloc.c\
			./src/memory/ft_memccpy.c\
			./src/memory/ft_memcmp.c\
			./src/memory/ft_memcpy.c\
			./src/memory/ft_memmove.c\
			./src/memory/ft_bzero.c\
			./src/multibytes/ft_unicode2utf8.c\
			./src/multibytes/ft_wcharsize.c\
			./src/multibytes/ft_wstrlen.c\
			./src/printf/ft_format_double_2.c\
			./src/printf/ft_format_grisu.c\
			./src/printf/ft_format_grisu_wsl.c\
			./src/printf/ft_format_handler.c\
			./src/printf/ft_format_parser.c\
			./src/printf/ft_vdprintf.c\
			./src/printf/ft_tmp2buff.c\
			./src/printf/ft_format_str.c\
			./src/printf/ft_format_int2str.c\
			./src/printf/ft_format_handler_wsl.c\
			./src/printf/ft_printf.c\
			./src/printf/ft_format_int_2.c\
			./src/printf/ft_format_str_wsl.c\
			./src/printf/ft_format_int_2_wsl.c\
			./src/printf/ft_format_double_3.c\
			./src/printf/ft_format_parser_wsl.c\
			./src/printf/ft_format_chr.c\
			./src/printf/ft_format_int_1.c\
			./src/printf/ft_format_double_1.c\
			./src/printf/ft_format_error.c\
			./src/stdio/ft_putnbr_fd.c\
			./src/stdio/ft_putchar_fd.c\
			./src/stdio/ft_putendl_fd.c\
			./src/stdio/ft_putstr_fd.c\
			./src/stdio/get_next_line.c\
			./src/string/ft_split.c\
			./src/string/ft_strchr.c\
			./src/string/ft_strtrim.c\
			./src/string/ft_strnstr.c\
			./src/string/ft_strmapi.c\
			./src/string/ft_strdup.c\
			./src/string/ft_atol.c\
			./src/string/ft_substr.c\
			./src/string/ft_strlcpy.c\
			./src/string/ft_strlen.c\
			./src/string/ft_strlcat.c\
			./src/string/ft_strrchr.c\
			./src/string/ft_strncmp.c\
			./src/string/ft_ltoa.c\
			./src/string/ft_strjoin.c\
			./src/string/ft_atoll.c\
			./src/string/ft_wcharsize.c\
			./src/string/ft_unicode2utf8.c\
			./src/t_fp/ft_fp2double.c\
			./src/t_fp/ft_normalize_fp.c\
			./src/t_fp/ft_double2fp.c\
			./src/t_fp/ft_multiply_fp.c\
			./src/t_fp/ft_minus_fp.c\
			./src/t_fp/ft_double2int_64.c\
			./src/vector/ft_growvec.c\
			./src/vector/ft_freevec.c\
			./src/vector/ft_newvec.c\
			./src/vector/ft_wstr2vec.c
