FROM	debian:buster

# Update Software Packages
RUN apt-get -qq update && apt-get -yqq upgrade
# To install ps
RUN apt-get -yqq install procps

# To install MariaDB (fork of MySQL)
RUN apt-get -yqq install mariadb-server


